# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore
from PyQt5.QtWidgets import QSplitter,QVBoxLayout,QDialog, QPushButton, QApplication, QTextEdit,QLineEdit
import sys


class Window(QDialog):
    def __init__(self):
        super().__init__()

        self.message = QLineEdit(self)
        self.message.resize(480,100)
        self.message.move(10,350)

        self.send_button = QPushButton("Send",self)
        self.send_button.resize(480,30)
        self.button_font = self.send_button.font()
        self.button_font.setPointSize(15)
        self.send_button.setFont(self.button_font)
        self.send_button.move(10,460)
        self.send_button.clicked.connect(self.send)

        self.chat_body = QVBoxLayout(self)
        splitter = QSplitter(QtCore.Qt.Vertical)

        self.chat = QTextEdit()
        self.chat.setReadOnly(True)

        splitter.addWidget(self.chat)
        splitter.addWidget(self.message)
        splitter.setSizes([400,100])

        splitter2 = QSplitter(QtCore.Qt.Vertical)
        splitter2.addWidget(splitter)
        splitter2.addWidget(self.send_button)
        splitter2.setSizes([200,10])

        self.chat_body.addWidget(splitter2)

        self.setWindowTitle("Login uzytkownika (opis uzytkownika)")
        self.resize(500, 500)

    def send(self):
        text = self.message.text()
        font = self.chat.font()
        font.setPointSize(13)        
        self.chat.setFont(font)
        self.chat.append("login: " + text)
        self.message.setText("")


if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = Window()
    window.exec()
    sys.exit(app.exec_())
