# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginPage(object):
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(342, 466)
        self.centralwidget = QtWidgets.QWidget(LoginPage)
        self.centralwidget.setObjectName("centralwidget")

        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(0, 40, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")

        self.name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.name_input.setGeometry(QtCore.QRect(40, 90, 261, 22))
        self.name_input.setClearButtonEnabled(True)
        self.name_input.setObjectName("name_input")

        self.login_input = QtWidgets.QLineEdit(self.centralwidget)
        self.login_input.setGeometry(QtCore.QRect(40, 120, 261, 22))
        self.login_input.setClearButtonEnabled(True)
        self.login_input.setObjectName("login_input")

        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(40, 150, 261, 22))
        self.password_input.setAutoFillBackground(False)
        self.password_input.setClearButtonEnabled(True)
        self.password_input.setObjectName("password_input")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)

        self.sign_up_button = QtWidgets.QPushButton(self.centralwidget)
        self.sign_up_button.setGeometry(QtCore.QRect(40, 180, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.sign_up_button.setFont(font)
        self.sign_up_button.setObjectName("sign_up_button")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 240, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.login_input_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.login_input_2.setGeometry(QtCore.QRect(40, 300, 261, 22))
        self.login_input_2.setClearButtonEnabled(True)
        self.login_input_2.setObjectName("login_input_2")

        self.password_input_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input_2.setGeometry(QtCore.QRect(40, 330, 261, 22))
        self.password_input_2.setAutoFillBackground(False)
        self.password_input_2.setClearButtonEnabled(True)
        self.password_input_2.setObjectName("password_input_2")
        self.password_input_2.setEchoMode(QtWidgets.QLineEdit.Password)

        self.sing_in_button = QtWidgets.QPushButton(self.centralwidget)
        self.sing_in_button.setGeometry(QtCore.QRect(40, 360, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.sing_in_button.setFont(font)
        self.sing_in_button.setObjectName("sing_in_button")

        LoginPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 342, 26))
        self.menubar.setObjectName("menubar")
        LoginPage.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(LoginPage)
        self.statusbar.setObjectName("statusbar")
        LoginPage.setStatusBar(self.statusbar)

        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "Gadu Gadu"))
        self.label_1.setText(_translate("LoginPage", "Need an account?"))
        self.login_input.setText(_translate("LoginPage", "Login"))
        self.password_input.setText(_translate("LoginPage", "Password"))
        self.sign_up_button.setText(_translate("LoginPage", "Sign up"))
        self.label_2.setText(_translate("LoginPage", "Already a user?"))
        self.login_input_2.setText(_translate("LoginPage", "Login"))
        self.sing_in_button.setText(_translate("LoginPage", "Sign in"))
        self.password_input_2.setText(_translate("LoginPage", "Password"))
        self.name_input.setText(_translate("LoginPage", "Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginPage = QtWidgets.QMainWindow()
    ui = Ui_LoginPage()
    ui.setupUi(LoginPage)
    LoginPage.show()
    sys.exit(app.exec_())
